# Generated by Django 5.2.8 on 2025-11-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UPC', models.CharField(default=0, max_length=5)),
                ('Name', models.CharField(default='Cheese', max_length=50)),
                ('Price', models.FloatField(default=0.0)),
            ],
        ),
    ]
